[build]
  command = "flutter build web --release"
  publish = "build/web"

# Ensures Flutter Web Pages Redirection (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Install Flutter while building (plugin ready)
[[plugins]]
  package = "netlify-plugin-flutter"
